/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSalesPurchaseRequestRouteImport } from './routes/_authenticated/sales/purchase-request'
import { Route as AuthenticatedSalesCollectionRouteImport } from './routes/_authenticated/sales/collection'
import { Route as AuthenticatedPurchaseOrderRouteImport } from './routes/_authenticated/purchase/order'
import { Route as AuthenticatedPurchaseCollectionRouteImport } from './routes/_authenticated/purchase/collection'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCommonNoticeRouteImport } from './routes/_authenticated/common/notice'
import { Route as AuthenticatedCommonCodeRouteImport } from './routes/_authenticated/common/code'
import { Route as AuthenticatedAccountingJournalEntriesRouteImport } from './routes/_authenticated/accounting/journal-entries'
import { Route as AuthenticatedAccountingAccountsRouteImport } from './routes/_authenticated/accounting/accounts'
import { Route as AuthenticatedHrEmployeesIndexRouteImport } from './routes/_authenticated/hr/employees/index'
import { Route as AuthenticatedHrDepartmentsIndexRouteImport } from './routes/_authenticated/hr/departments/index'
import { Route as AuthenticatedSalesTaxInvoiceStatusRouteImport } from './routes/_authenticated/sales/tax-invoice/status'
import { Route as AuthenticatedSalesTaxInvoiceIssueRouteImport } from './routes/_authenticated/sales/tax-invoice/issue'
import { Route as AuthenticatedSalesContractValidateRouteImport } from './routes/_authenticated/sales/contract/validate'
import { Route as AuthenticatedSalesContractRegisterRouteImport } from './routes/_authenticated/sales/contract/register'
import { Route as AuthenticatedSalesContractProposalRouteImport } from './routes/_authenticated/sales/contract/proposal'
import { Route as AuthenticatedSalesContractPerformanceRouteImport } from './routes/_authenticated/sales/contract/performance'
import { Route as AuthenticatedSalesContractItemsRouteImport } from './routes/_authenticated/sales/contract/items'
import { Route as AuthenticatedPurchasePaymentStatusRouteImport } from './routes/_authenticated/purchase/payment/status'
import { Route as AuthenticatedPurchasePaymentApprovalRouteImport } from './routes/_authenticated/purchase/payment/approval'
import { Route as AuthenticatedPurchaseBillStatusRouteImport } from './routes/_authenticated/purchase/bill/status'
import { Route as AuthenticatedPurchaseBillServiceRouteImport } from './routes/_authenticated/purchase/bill/service'
import { Route as AuthenticatedPurchaseBillGoodsRouteImport } from './routes/_authenticated/purchase/bill/goods'
import { Route as AuthenticatedPmUtilizationPersonalRouteImport } from './routes/_authenticated/pm/utilization/personal'
import { Route as AuthenticatedPmBudgetTeamActualRouteImport } from './routes/_authenticated/pm/budget/team-actual'
import { Route as AuthenticatedPmBudgetProjectActualRouteImport } from './routes/_authenticated/pm/budget/project-actual'
import { Route as AuthenticatedPmActivityViewRouteImport } from './routes/_authenticated/pm/activity/view'
import { Route as AuthenticatedPmActivityRegisterRouteImport } from './routes/_authenticated/pm/activity/register'
import { Route as AuthenticatedHrPersonalHistoryRouteImport } from './routes/_authenticated/hr/personal/history'
import { Route as AuthenticatedHrPersonalEducationRouteImport } from './routes/_authenticated/hr/personal/education'
import { Route as AuthenticatedHrPayrollPayslipRouteImport } from './routes/_authenticated/hr/payroll/payslip'
import { Route as AuthenticatedHrPayrollIncentiveStatusRouteImport } from './routes/_authenticated/hr/payroll/incentive-status'
import { Route as AuthenticatedHrPayrollExpenseStatementRouteImport } from './routes/_authenticated/hr/payroll/expense-statement'
import { Route as AuthenticatedHrEducationHistoryRouteImport } from './routes/_authenticated/hr/education/history'
import { Route as AuthenticatedHrEducationExternalApplyRouteImport } from './routes/_authenticated/hr/education/external-apply'
import { Route as AuthenticatedHrEducationCertApplyRouteImport } from './routes/_authenticated/hr/education/cert-apply'
import { Route as AuthenticatedHrAttendanceViewRouteImport } from './routes/_authenticated/hr/attendance/view'
import { Route as AuthenticatedHrAttendanceRegisterRouteImport } from './routes/_authenticated/hr/attendance/register'
import { Route as AuthenticatedHrAttendanceOvertimeApplyRouteImport } from './routes/_authenticated/hr/attendance/overtime-apply'
import { Route as AuthenticatedHrAttendanceLeaveStatusRouteImport } from './routes/_authenticated/hr/attendance/leave-status'
import { Route as AuthenticatedHrAttendanceLeaveApplyRouteImport } from './routes/_authenticated/hr/attendance/leave-apply'
import { Route as AuthenticatedGaSealUseExportRouteImport } from './routes/_authenticated/ga/seal/use-export'
import { Route as AuthenticatedGaSealUseApplyRouteImport } from './routes/_authenticated/ga/seal/use-apply'
import { Route as AuthenticatedGaSealFingerprintExportRouteImport } from './routes/_authenticated/ga/seal/fingerprint-export'
import { Route as AuthenticatedGaSealEContractRouteImport } from './routes/_authenticated/ga/seal/e-contract'
import { Route as AuthenticatedGaSealCorporateApplyRouteImport } from './routes/_authenticated/ga/seal/corporate-apply'
import { Route as AuthenticatedGaExpenseVehicleSubsidyRouteImport } from './routes/_authenticated/ga/expense/vehicle-subsidy'
import { Route as AuthenticatedGaExpenseTuitionRouteImport } from './routes/_authenticated/ga/expense/tuition'
import { Route as AuthenticatedGaExpenseTransportRouteImport } from './routes/_authenticated/ga/expense/transport'
import { Route as AuthenticatedGaExpenseMealTicketRouteImport } from './routes/_authenticated/ga/expense/meal-ticket'
import { Route as AuthenticatedGaExpenseDisbursementRouteImport } from './routes/_authenticated/ga/expense/disbursement'
import { Route as AuthenticatedGaExpenseCongratulationRouteImport } from './routes/_authenticated/ga/expense/congratulation'
import { Route as AuthenticatedFinanceVoucherByDateRouteImport } from './routes/_authenticated/finance/voucher/by-date'
import { Route as AuthenticatedFinanceVoucherByAccountRouteImport } from './routes/_authenticated/finance/voucher/by-account'
import { Route as AuthenticatedFinanceCardUsageRouteImport } from './routes/_authenticated/finance/card/usage'
import { Route as AuthenticatedFinanceCardStatusRouteImport } from './routes/_authenticated/finance/card/status'
import { Route as AuthenticatedFinanceCardBillingRouteImport } from './routes/_authenticated/finance/card/billing'
import { Route as AuthenticatedEvalProgressStatusRouteImport } from './routes/_authenticated/eval/progress/status'
import { Route as AuthenticatedEvalProgressEvaluateeRouteImport } from './routes/_authenticated/eval/progress/evaluatee'
import { Route as AuthenticatedEvalGoalRegisterRouteImport } from './routes/_authenticated/eval/goal/register'
import { Route as AuthenticatedEvalAppraisalSelfRouteImport } from './routes/_authenticated/eval/appraisal/self'
import { Route as AuthenticatedEvalAppraisalReviewRouteImport } from './routes/_authenticated/eval/appraisal/review'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSalesPurchaseRequestRoute =
  AuthenticatedSalesPurchaseRequestRouteImport.update({
    id: '/sales/purchase-request',
    path: '/sales/purchase-request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesCollectionRoute =
  AuthenticatedSalesCollectionRouteImport.update({
    id: '/sales/collection',
    path: '/sales/collection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrderRoute =
  AuthenticatedPurchaseOrderRouteImport.update({
    id: '/purchase/order',
    path: '/purchase/order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseCollectionRoute =
  AuthenticatedPurchaseCollectionRouteImport.update({
    id: '/purchase/collection',
    path: '/purchase/collection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommonNoticeRoute =
  AuthenticatedCommonNoticeRouteImport.update({
    id: '/common/notice',
    path: '/common/notice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommonCodeRoute = AuthenticatedCommonCodeRouteImport.update({
  id: '/common/code',
  path: '/common/code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingJournalEntriesRoute =
  AuthenticatedAccountingJournalEntriesRouteImport.update({
    id: '/accounting/journal-entries',
    path: '/accounting/journal-entries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingAccountsRoute =
  AuthenticatedAccountingAccountsRouteImport.update({
    id: '/accounting/accounts',
    path: '/accounting/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEmployeesIndexRoute =
  AuthenticatedHrEmployeesIndexRouteImport.update({
    id: '/hr/employees/',
    path: '/hr/employees/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrDepartmentsIndexRoute =
  AuthenticatedHrDepartmentsIndexRouteImport.update({
    id: '/hr/departments/',
    path: '/hr/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesTaxInvoiceStatusRoute =
  AuthenticatedSalesTaxInvoiceStatusRouteImport.update({
    id: '/sales/tax-invoice/status',
    path: '/sales/tax-invoice/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesTaxInvoiceIssueRoute =
  AuthenticatedSalesTaxInvoiceIssueRouteImport.update({
    id: '/sales/tax-invoice/issue',
    path: '/sales/tax-invoice/issue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesContractValidateRoute =
  AuthenticatedSalesContractValidateRouteImport.update({
    id: '/sales/contract/validate',
    path: '/sales/contract/validate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesContractRegisterRoute =
  AuthenticatedSalesContractRegisterRouteImport.update({
    id: '/sales/contract/register',
    path: '/sales/contract/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesContractProposalRoute =
  AuthenticatedSalesContractProposalRouteImport.update({
    id: '/sales/contract/proposal',
    path: '/sales/contract/proposal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesContractPerformanceRoute =
  AuthenticatedSalesContractPerformanceRouteImport.update({
    id: '/sales/contract/performance',
    path: '/sales/contract/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesContractItemsRoute =
  AuthenticatedSalesContractItemsRouteImport.update({
    id: '/sales/contract/items',
    path: '/sales/contract/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasePaymentStatusRoute =
  AuthenticatedPurchasePaymentStatusRouteImport.update({
    id: '/purchase/payment/status',
    path: '/purchase/payment/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchasePaymentApprovalRoute =
  AuthenticatedPurchasePaymentApprovalRouteImport.update({
    id: '/purchase/payment/approval',
    path: '/purchase/payment/approval',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillStatusRoute =
  AuthenticatedPurchaseBillStatusRouteImport.update({
    id: '/purchase/bill/status',
    path: '/purchase/bill/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillServiceRoute =
  AuthenticatedPurchaseBillServiceRouteImport.update({
    id: '/purchase/bill/service',
    path: '/purchase/bill/service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseBillGoodsRoute =
  AuthenticatedPurchaseBillGoodsRouteImport.update({
    id: '/purchase/bill/goods',
    path: '/purchase/bill/goods',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmUtilizationPersonalRoute =
  AuthenticatedPmUtilizationPersonalRouteImport.update({
    id: '/pm/utilization/personal',
    path: '/pm/utilization/personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmBudgetTeamActualRoute =
  AuthenticatedPmBudgetTeamActualRouteImport.update({
    id: '/pm/budget/team-actual',
    path: '/pm/budget/team-actual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmBudgetProjectActualRoute =
  AuthenticatedPmBudgetProjectActualRouteImport.update({
    id: '/pm/budget/project-actual',
    path: '/pm/budget/project-actual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmActivityViewRoute =
  AuthenticatedPmActivityViewRouteImport.update({
    id: '/pm/activity/view',
    path: '/pm/activity/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPmActivityRegisterRoute =
  AuthenticatedPmActivityRegisterRouteImport.update({
    id: '/pm/activity/register',
    path: '/pm/activity/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPersonalHistoryRoute =
  AuthenticatedHrPersonalHistoryRouteImport.update({
    id: '/hr/personal/history',
    path: '/hr/personal/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPersonalEducationRoute =
  AuthenticatedHrPersonalEducationRouteImport.update({
    id: '/hr/personal/education',
    path: '/hr/personal/education',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPayrollPayslipRoute =
  AuthenticatedHrPayrollPayslipRouteImport.update({
    id: '/hr/payroll/payslip',
    path: '/hr/payroll/payslip',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPayrollIncentiveStatusRoute =
  AuthenticatedHrPayrollIncentiveStatusRouteImport.update({
    id: '/hr/payroll/incentive-status',
    path: '/hr/payroll/incentive-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPayrollExpenseStatementRoute =
  AuthenticatedHrPayrollExpenseStatementRouteImport.update({
    id: '/hr/payroll/expense-statement',
    path: '/hr/payroll/expense-statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEducationHistoryRoute =
  AuthenticatedHrEducationHistoryRouteImport.update({
    id: '/hr/education/history',
    path: '/hr/education/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEducationExternalApplyRoute =
  AuthenticatedHrEducationExternalApplyRouteImport.update({
    id: '/hr/education/external-apply',
    path: '/hr/education/external-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrEducationCertApplyRoute =
  AuthenticatedHrEducationCertApplyRouteImport.update({
    id: '/hr/education/cert-apply',
    path: '/hr/education/cert-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceViewRoute =
  AuthenticatedHrAttendanceViewRouteImport.update({
    id: '/hr/attendance/view',
    path: '/hr/attendance/view',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceRegisterRoute =
  AuthenticatedHrAttendanceRegisterRouteImport.update({
    id: '/hr/attendance/register',
    path: '/hr/attendance/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceOvertimeApplyRoute =
  AuthenticatedHrAttendanceOvertimeApplyRouteImport.update({
    id: '/hr/attendance/overtime-apply',
    path: '/hr/attendance/overtime-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceLeaveStatusRoute =
  AuthenticatedHrAttendanceLeaveStatusRouteImport.update({
    id: '/hr/attendance/leave-status',
    path: '/hr/attendance/leave-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrAttendanceLeaveApplyRoute =
  AuthenticatedHrAttendanceLeaveApplyRouteImport.update({
    id: '/hr/attendance/leave-apply',
    path: '/hr/attendance/leave-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaSealUseExportRoute =
  AuthenticatedGaSealUseExportRouteImport.update({
    id: '/ga/seal/use-export',
    path: '/ga/seal/use-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaSealUseApplyRoute =
  AuthenticatedGaSealUseApplyRouteImport.update({
    id: '/ga/seal/use-apply',
    path: '/ga/seal/use-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaSealFingerprintExportRoute =
  AuthenticatedGaSealFingerprintExportRouteImport.update({
    id: '/ga/seal/fingerprint-export',
    path: '/ga/seal/fingerprint-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaSealEContractRoute =
  AuthenticatedGaSealEContractRouteImport.update({
    id: '/ga/seal/e-contract',
    path: '/ga/seal/e-contract',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaSealCorporateApplyRoute =
  AuthenticatedGaSealCorporateApplyRouteImport.update({
    id: '/ga/seal/corporate-apply',
    path: '/ga/seal/corporate-apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseVehicleSubsidyRoute =
  AuthenticatedGaExpenseVehicleSubsidyRouteImport.update({
    id: '/ga/expense/vehicle-subsidy',
    path: '/ga/expense/vehicle-subsidy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseTuitionRoute =
  AuthenticatedGaExpenseTuitionRouteImport.update({
    id: '/ga/expense/tuition',
    path: '/ga/expense/tuition',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseTransportRoute =
  AuthenticatedGaExpenseTransportRouteImport.update({
    id: '/ga/expense/transport',
    path: '/ga/expense/transport',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseMealTicketRoute =
  AuthenticatedGaExpenseMealTicketRouteImport.update({
    id: '/ga/expense/meal-ticket',
    path: '/ga/expense/meal-ticket',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseDisbursementRoute =
  AuthenticatedGaExpenseDisbursementRouteImport.update({
    id: '/ga/expense/disbursement',
    path: '/ga/expense/disbursement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGaExpenseCongratulationRoute =
  AuthenticatedGaExpenseCongratulationRouteImport.update({
    id: '/ga/expense/congratulation',
    path: '/ga/expense/congratulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceVoucherByDateRoute =
  AuthenticatedFinanceVoucherByDateRouteImport.update({
    id: '/finance/voucher/by-date',
    path: '/finance/voucher/by-date',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceVoucherByAccountRoute =
  AuthenticatedFinanceVoucherByAccountRouteImport.update({
    id: '/finance/voucher/by-account',
    path: '/finance/voucher/by-account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCardUsageRoute =
  AuthenticatedFinanceCardUsageRouteImport.update({
    id: '/finance/card/usage',
    path: '/finance/card/usage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCardStatusRoute =
  AuthenticatedFinanceCardStatusRouteImport.update({
    id: '/finance/card/status',
    path: '/finance/card/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCardBillingRoute =
  AuthenticatedFinanceCardBillingRouteImport.update({
    id: '/finance/card/billing',
    path: '/finance/card/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvalProgressStatusRoute =
  AuthenticatedEvalProgressStatusRouteImport.update({
    id: '/eval/progress/status',
    path: '/eval/progress/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvalProgressEvaluateeRoute =
  AuthenticatedEvalProgressEvaluateeRouteImport.update({
    id: '/eval/progress/evaluatee',
    path: '/eval/progress/evaluatee',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvalGoalRegisterRoute =
  AuthenticatedEvalGoalRegisterRouteImport.update({
    id: '/eval/goal/register',
    path: '/eval/goal/register',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvalAppraisalSelfRoute =
  AuthenticatedEvalAppraisalSelfRouteImport.update({
    id: '/eval/appraisal/self',
    path: '/eval/appraisal/self',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvalAppraisalReviewRoute =
  AuthenticatedEvalAppraisalReviewRouteImport.update({
    id: '/eval/appraisal/review',
    path: '/eval/appraisal/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/journal-entries': typeof AuthenticatedAccountingJournalEntriesRoute
  '/common/code': typeof AuthenticatedCommonCodeRoute
  '/common/notice': typeof AuthenticatedCommonNoticeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/purchase/collection': typeof AuthenticatedPurchaseCollectionRoute
  '/purchase/order': typeof AuthenticatedPurchaseOrderRoute
  '/sales/collection': typeof AuthenticatedSalesCollectionRoute
  '/sales/purchase-request': typeof AuthenticatedSalesPurchaseRequestRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/eval/appraisal/review': typeof AuthenticatedEvalAppraisalReviewRoute
  '/eval/appraisal/self': typeof AuthenticatedEvalAppraisalSelfRoute
  '/eval/goal/register': typeof AuthenticatedEvalGoalRegisterRoute
  '/eval/progress/evaluatee': typeof AuthenticatedEvalProgressEvaluateeRoute
  '/eval/progress/status': typeof AuthenticatedEvalProgressStatusRoute
  '/finance/card/billing': typeof AuthenticatedFinanceCardBillingRoute
  '/finance/card/status': typeof AuthenticatedFinanceCardStatusRoute
  '/finance/card/usage': typeof AuthenticatedFinanceCardUsageRoute
  '/finance/voucher/by-account': typeof AuthenticatedFinanceVoucherByAccountRoute
  '/finance/voucher/by-date': typeof AuthenticatedFinanceVoucherByDateRoute
  '/ga/expense/congratulation': typeof AuthenticatedGaExpenseCongratulationRoute
  '/ga/expense/disbursement': typeof AuthenticatedGaExpenseDisbursementRoute
  '/ga/expense/meal-ticket': typeof AuthenticatedGaExpenseMealTicketRoute
  '/ga/expense/transport': typeof AuthenticatedGaExpenseTransportRoute
  '/ga/expense/tuition': typeof AuthenticatedGaExpenseTuitionRoute
  '/ga/expense/vehicle-subsidy': typeof AuthenticatedGaExpenseVehicleSubsidyRoute
  '/ga/seal/corporate-apply': typeof AuthenticatedGaSealCorporateApplyRoute
  '/ga/seal/e-contract': typeof AuthenticatedGaSealEContractRoute
  '/ga/seal/fingerprint-export': typeof AuthenticatedGaSealFingerprintExportRoute
  '/ga/seal/use-apply': typeof AuthenticatedGaSealUseApplyRoute
  '/ga/seal/use-export': typeof AuthenticatedGaSealUseExportRoute
  '/hr/attendance/leave-apply': typeof AuthenticatedHrAttendanceLeaveApplyRoute
  '/hr/attendance/leave-status': typeof AuthenticatedHrAttendanceLeaveStatusRoute
  '/hr/attendance/overtime-apply': typeof AuthenticatedHrAttendanceOvertimeApplyRoute
  '/hr/attendance/register': typeof AuthenticatedHrAttendanceRegisterRoute
  '/hr/attendance/view': typeof AuthenticatedHrAttendanceViewRoute
  '/hr/education/cert-apply': typeof AuthenticatedHrEducationCertApplyRoute
  '/hr/education/external-apply': typeof AuthenticatedHrEducationExternalApplyRoute
  '/hr/education/history': typeof AuthenticatedHrEducationHistoryRoute
  '/hr/payroll/expense-statement': typeof AuthenticatedHrPayrollExpenseStatementRoute
  '/hr/payroll/incentive-status': typeof AuthenticatedHrPayrollIncentiveStatusRoute
  '/hr/payroll/payslip': typeof AuthenticatedHrPayrollPayslipRoute
  '/hr/personal/education': typeof AuthenticatedHrPersonalEducationRoute
  '/hr/personal/history': typeof AuthenticatedHrPersonalHistoryRoute
  '/pm/activity/register': typeof AuthenticatedPmActivityRegisterRoute
  '/pm/activity/view': typeof AuthenticatedPmActivityViewRoute
  '/pm/budget/project-actual': typeof AuthenticatedPmBudgetProjectActualRoute
  '/pm/budget/team-actual': typeof AuthenticatedPmBudgetTeamActualRoute
  '/pm/utilization/personal': typeof AuthenticatedPmUtilizationPersonalRoute
  '/purchase/bill/goods': typeof AuthenticatedPurchaseBillGoodsRoute
  '/purchase/bill/service': typeof AuthenticatedPurchaseBillServiceRoute
  '/purchase/bill/status': typeof AuthenticatedPurchaseBillStatusRoute
  '/purchase/payment/approval': typeof AuthenticatedPurchasePaymentApprovalRoute
  '/purchase/payment/status': typeof AuthenticatedPurchasePaymentStatusRoute
  '/sales/contract/items': typeof AuthenticatedSalesContractItemsRoute
  '/sales/contract/performance': typeof AuthenticatedSalesContractPerformanceRoute
  '/sales/contract/proposal': typeof AuthenticatedSalesContractProposalRoute
  '/sales/contract/register': typeof AuthenticatedSalesContractRegisterRoute
  '/sales/contract/validate': typeof AuthenticatedSalesContractValidateRoute
  '/sales/tax-invoice/issue': typeof AuthenticatedSalesTaxInvoiceIssueRoute
  '/sales/tax-invoice/status': typeof AuthenticatedSalesTaxInvoiceStatusRoute
  '/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/employees/': typeof AuthenticatedHrEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/$': typeof AuthenticatedSplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/accounting/journal-entries': typeof AuthenticatedAccountingJournalEntriesRoute
  '/common/code': typeof AuthenticatedCommonCodeRoute
  '/common/notice': typeof AuthenticatedCommonNoticeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/purchase/collection': typeof AuthenticatedPurchaseCollectionRoute
  '/purchase/order': typeof AuthenticatedPurchaseOrderRoute
  '/sales/collection': typeof AuthenticatedSalesCollectionRoute
  '/sales/purchase-request': typeof AuthenticatedSalesPurchaseRequestRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/eval/appraisal/review': typeof AuthenticatedEvalAppraisalReviewRoute
  '/eval/appraisal/self': typeof AuthenticatedEvalAppraisalSelfRoute
  '/eval/goal/register': typeof AuthenticatedEvalGoalRegisterRoute
  '/eval/progress/evaluatee': typeof AuthenticatedEvalProgressEvaluateeRoute
  '/eval/progress/status': typeof AuthenticatedEvalProgressStatusRoute
  '/finance/card/billing': typeof AuthenticatedFinanceCardBillingRoute
  '/finance/card/status': typeof AuthenticatedFinanceCardStatusRoute
  '/finance/card/usage': typeof AuthenticatedFinanceCardUsageRoute
  '/finance/voucher/by-account': typeof AuthenticatedFinanceVoucherByAccountRoute
  '/finance/voucher/by-date': typeof AuthenticatedFinanceVoucherByDateRoute
  '/ga/expense/congratulation': typeof AuthenticatedGaExpenseCongratulationRoute
  '/ga/expense/disbursement': typeof AuthenticatedGaExpenseDisbursementRoute
  '/ga/expense/meal-ticket': typeof AuthenticatedGaExpenseMealTicketRoute
  '/ga/expense/transport': typeof AuthenticatedGaExpenseTransportRoute
  '/ga/expense/tuition': typeof AuthenticatedGaExpenseTuitionRoute
  '/ga/expense/vehicle-subsidy': typeof AuthenticatedGaExpenseVehicleSubsidyRoute
  '/ga/seal/corporate-apply': typeof AuthenticatedGaSealCorporateApplyRoute
  '/ga/seal/e-contract': typeof AuthenticatedGaSealEContractRoute
  '/ga/seal/fingerprint-export': typeof AuthenticatedGaSealFingerprintExportRoute
  '/ga/seal/use-apply': typeof AuthenticatedGaSealUseApplyRoute
  '/ga/seal/use-export': typeof AuthenticatedGaSealUseExportRoute
  '/hr/attendance/leave-apply': typeof AuthenticatedHrAttendanceLeaveApplyRoute
  '/hr/attendance/leave-status': typeof AuthenticatedHrAttendanceLeaveStatusRoute
  '/hr/attendance/overtime-apply': typeof AuthenticatedHrAttendanceOvertimeApplyRoute
  '/hr/attendance/register': typeof AuthenticatedHrAttendanceRegisterRoute
  '/hr/attendance/view': typeof AuthenticatedHrAttendanceViewRoute
  '/hr/education/cert-apply': typeof AuthenticatedHrEducationCertApplyRoute
  '/hr/education/external-apply': typeof AuthenticatedHrEducationExternalApplyRoute
  '/hr/education/history': typeof AuthenticatedHrEducationHistoryRoute
  '/hr/payroll/expense-statement': typeof AuthenticatedHrPayrollExpenseStatementRoute
  '/hr/payroll/incentive-status': typeof AuthenticatedHrPayrollIncentiveStatusRoute
  '/hr/payroll/payslip': typeof AuthenticatedHrPayrollPayslipRoute
  '/hr/personal/education': typeof AuthenticatedHrPersonalEducationRoute
  '/hr/personal/history': typeof AuthenticatedHrPersonalHistoryRoute
  '/pm/activity/register': typeof AuthenticatedPmActivityRegisterRoute
  '/pm/activity/view': typeof AuthenticatedPmActivityViewRoute
  '/pm/budget/project-actual': typeof AuthenticatedPmBudgetProjectActualRoute
  '/pm/budget/team-actual': typeof AuthenticatedPmBudgetTeamActualRoute
  '/pm/utilization/personal': typeof AuthenticatedPmUtilizationPersonalRoute
  '/purchase/bill/goods': typeof AuthenticatedPurchaseBillGoodsRoute
  '/purchase/bill/service': typeof AuthenticatedPurchaseBillServiceRoute
  '/purchase/bill/status': typeof AuthenticatedPurchaseBillStatusRoute
  '/purchase/payment/approval': typeof AuthenticatedPurchasePaymentApprovalRoute
  '/purchase/payment/status': typeof AuthenticatedPurchasePaymentStatusRoute
  '/sales/contract/items': typeof AuthenticatedSalesContractItemsRoute
  '/sales/contract/performance': typeof AuthenticatedSalesContractPerformanceRoute
  '/sales/contract/proposal': typeof AuthenticatedSalesContractProposalRoute
  '/sales/contract/register': typeof AuthenticatedSalesContractRegisterRoute
  '/sales/contract/validate': typeof AuthenticatedSalesContractValidateRoute
  '/sales/tax-invoice/issue': typeof AuthenticatedSalesTaxInvoiceIssueRoute
  '/sales/tax-invoice/status': typeof AuthenticatedSalesTaxInvoiceStatusRoute
  '/hr/departments': typeof AuthenticatedHrDepartmentsIndexRoute
  '/hr/employees': typeof AuthenticatedHrEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/accounts': typeof AuthenticatedAccountingAccountsRoute
  '/_authenticated/accounting/journal-entries': typeof AuthenticatedAccountingJournalEntriesRoute
  '/_authenticated/common/code': typeof AuthenticatedCommonCodeRoute
  '/_authenticated/common/notice': typeof AuthenticatedCommonNoticeRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/purchase/collection': typeof AuthenticatedPurchaseCollectionRoute
  '/_authenticated/purchase/order': typeof AuthenticatedPurchaseOrderRoute
  '/_authenticated/sales/collection': typeof AuthenticatedSalesCollectionRoute
  '/_authenticated/sales/purchase-request': typeof AuthenticatedSalesPurchaseRequestRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/eval/appraisal/review': typeof AuthenticatedEvalAppraisalReviewRoute
  '/_authenticated/eval/appraisal/self': typeof AuthenticatedEvalAppraisalSelfRoute
  '/_authenticated/eval/goal/register': typeof AuthenticatedEvalGoalRegisterRoute
  '/_authenticated/eval/progress/evaluatee': typeof AuthenticatedEvalProgressEvaluateeRoute
  '/_authenticated/eval/progress/status': typeof AuthenticatedEvalProgressStatusRoute
  '/_authenticated/finance/card/billing': typeof AuthenticatedFinanceCardBillingRoute
  '/_authenticated/finance/card/status': typeof AuthenticatedFinanceCardStatusRoute
  '/_authenticated/finance/card/usage': typeof AuthenticatedFinanceCardUsageRoute
  '/_authenticated/finance/voucher/by-account': typeof AuthenticatedFinanceVoucherByAccountRoute
  '/_authenticated/finance/voucher/by-date': typeof AuthenticatedFinanceVoucherByDateRoute
  '/_authenticated/ga/expense/congratulation': typeof AuthenticatedGaExpenseCongratulationRoute
  '/_authenticated/ga/expense/disbursement': typeof AuthenticatedGaExpenseDisbursementRoute
  '/_authenticated/ga/expense/meal-ticket': typeof AuthenticatedGaExpenseMealTicketRoute
  '/_authenticated/ga/expense/transport': typeof AuthenticatedGaExpenseTransportRoute
  '/_authenticated/ga/expense/tuition': typeof AuthenticatedGaExpenseTuitionRoute
  '/_authenticated/ga/expense/vehicle-subsidy': typeof AuthenticatedGaExpenseVehicleSubsidyRoute
  '/_authenticated/ga/seal/corporate-apply': typeof AuthenticatedGaSealCorporateApplyRoute
  '/_authenticated/ga/seal/e-contract': typeof AuthenticatedGaSealEContractRoute
  '/_authenticated/ga/seal/fingerprint-export': typeof AuthenticatedGaSealFingerprintExportRoute
  '/_authenticated/ga/seal/use-apply': typeof AuthenticatedGaSealUseApplyRoute
  '/_authenticated/ga/seal/use-export': typeof AuthenticatedGaSealUseExportRoute
  '/_authenticated/hr/attendance/leave-apply': typeof AuthenticatedHrAttendanceLeaveApplyRoute
  '/_authenticated/hr/attendance/leave-status': typeof AuthenticatedHrAttendanceLeaveStatusRoute
  '/_authenticated/hr/attendance/overtime-apply': typeof AuthenticatedHrAttendanceOvertimeApplyRoute
  '/_authenticated/hr/attendance/register': typeof AuthenticatedHrAttendanceRegisterRoute
  '/_authenticated/hr/attendance/view': typeof AuthenticatedHrAttendanceViewRoute
  '/_authenticated/hr/education/cert-apply': typeof AuthenticatedHrEducationCertApplyRoute
  '/_authenticated/hr/education/external-apply': typeof AuthenticatedHrEducationExternalApplyRoute
  '/_authenticated/hr/education/history': typeof AuthenticatedHrEducationHistoryRoute
  '/_authenticated/hr/payroll/expense-statement': typeof AuthenticatedHrPayrollExpenseStatementRoute
  '/_authenticated/hr/payroll/incentive-status': typeof AuthenticatedHrPayrollIncentiveStatusRoute
  '/_authenticated/hr/payroll/payslip': typeof AuthenticatedHrPayrollPayslipRoute
  '/_authenticated/hr/personal/education': typeof AuthenticatedHrPersonalEducationRoute
  '/_authenticated/hr/personal/history': typeof AuthenticatedHrPersonalHistoryRoute
  '/_authenticated/pm/activity/register': typeof AuthenticatedPmActivityRegisterRoute
  '/_authenticated/pm/activity/view': typeof AuthenticatedPmActivityViewRoute
  '/_authenticated/pm/budget/project-actual': typeof AuthenticatedPmBudgetProjectActualRoute
  '/_authenticated/pm/budget/team-actual': typeof AuthenticatedPmBudgetTeamActualRoute
  '/_authenticated/pm/utilization/personal': typeof AuthenticatedPmUtilizationPersonalRoute
  '/_authenticated/purchase/bill/goods': typeof AuthenticatedPurchaseBillGoodsRoute
  '/_authenticated/purchase/bill/service': typeof AuthenticatedPurchaseBillServiceRoute
  '/_authenticated/purchase/bill/status': typeof AuthenticatedPurchaseBillStatusRoute
  '/_authenticated/purchase/payment/approval': typeof AuthenticatedPurchasePaymentApprovalRoute
  '/_authenticated/purchase/payment/status': typeof AuthenticatedPurchasePaymentStatusRoute
  '/_authenticated/sales/contract/items': typeof AuthenticatedSalesContractItemsRoute
  '/_authenticated/sales/contract/performance': typeof AuthenticatedSalesContractPerformanceRoute
  '/_authenticated/sales/contract/proposal': typeof AuthenticatedSalesContractProposalRoute
  '/_authenticated/sales/contract/register': typeof AuthenticatedSalesContractRegisterRoute
  '/_authenticated/sales/contract/validate': typeof AuthenticatedSalesContractValidateRoute
  '/_authenticated/sales/tax-invoice/issue': typeof AuthenticatedSalesTaxInvoiceIssueRoute
  '/_authenticated/sales/tax-invoice/status': typeof AuthenticatedSalesTaxInvoiceStatusRoute
  '/_authenticated/hr/departments/': typeof AuthenticatedHrDepartmentsIndexRoute
  '/_authenticated/hr/employees/': typeof AuthenticatedHrEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/accounting/accounts'
    | '/accounting/journal-entries'
    | '/common/code'
    | '/common/notice'
    | '/errors/$error'
    | '/purchase/collection'
    | '/purchase/order'
    | '/sales/collection'
    | '/sales/purchase-request'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats/'
    | '/customers/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/eval/appraisal/review'
    | '/eval/appraisal/self'
    | '/eval/goal/register'
    | '/eval/progress/evaluatee'
    | '/eval/progress/status'
    | '/finance/card/billing'
    | '/finance/card/status'
    | '/finance/card/usage'
    | '/finance/voucher/by-account'
    | '/finance/voucher/by-date'
    | '/ga/expense/congratulation'
    | '/ga/expense/disbursement'
    | '/ga/expense/meal-ticket'
    | '/ga/expense/transport'
    | '/ga/expense/tuition'
    | '/ga/expense/vehicle-subsidy'
    | '/ga/seal/corporate-apply'
    | '/ga/seal/e-contract'
    | '/ga/seal/fingerprint-export'
    | '/ga/seal/use-apply'
    | '/ga/seal/use-export'
    | '/hr/attendance/leave-apply'
    | '/hr/attendance/leave-status'
    | '/hr/attendance/overtime-apply'
    | '/hr/attendance/register'
    | '/hr/attendance/view'
    | '/hr/education/cert-apply'
    | '/hr/education/external-apply'
    | '/hr/education/history'
    | '/hr/payroll/expense-statement'
    | '/hr/payroll/incentive-status'
    | '/hr/payroll/payslip'
    | '/hr/personal/education'
    | '/hr/personal/history'
    | '/pm/activity/register'
    | '/pm/activity/view'
    | '/pm/budget/project-actual'
    | '/pm/budget/team-actual'
    | '/pm/utilization/personal'
    | '/purchase/bill/goods'
    | '/purchase/bill/service'
    | '/purchase/bill/status'
    | '/purchase/payment/approval'
    | '/purchase/payment/status'
    | '/sales/contract/items'
    | '/sales/contract/performance'
    | '/sales/contract/proposal'
    | '/sales/contract/register'
    | '/sales/contract/validate'
    | '/sales/tax-invoice/issue'
    | '/sales/tax-invoice/status'
    | '/hr/departments/'
    | '/hr/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/$'
    | '/'
    | '/accounting/accounts'
    | '/accounting/journal-entries'
    | '/common/code'
    | '/common/notice'
    | '/errors/$error'
    | '/purchase/collection'
    | '/purchase/order'
    | '/sales/collection'
    | '/sales/purchase-request'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/chats'
    | '/customers'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/eval/appraisal/review'
    | '/eval/appraisal/self'
    | '/eval/goal/register'
    | '/eval/progress/evaluatee'
    | '/eval/progress/status'
    | '/finance/card/billing'
    | '/finance/card/status'
    | '/finance/card/usage'
    | '/finance/voucher/by-account'
    | '/finance/voucher/by-date'
    | '/ga/expense/congratulation'
    | '/ga/expense/disbursement'
    | '/ga/expense/meal-ticket'
    | '/ga/expense/transport'
    | '/ga/expense/tuition'
    | '/ga/expense/vehicle-subsidy'
    | '/ga/seal/corporate-apply'
    | '/ga/seal/e-contract'
    | '/ga/seal/fingerprint-export'
    | '/ga/seal/use-apply'
    | '/ga/seal/use-export'
    | '/hr/attendance/leave-apply'
    | '/hr/attendance/leave-status'
    | '/hr/attendance/overtime-apply'
    | '/hr/attendance/register'
    | '/hr/attendance/view'
    | '/hr/education/cert-apply'
    | '/hr/education/external-apply'
    | '/hr/education/history'
    | '/hr/payroll/expense-statement'
    | '/hr/payroll/incentive-status'
    | '/hr/payroll/payslip'
    | '/hr/personal/education'
    | '/hr/personal/history'
    | '/pm/activity/register'
    | '/pm/activity/view'
    | '/pm/budget/project-actual'
    | '/pm/budget/team-actual'
    | '/pm/utilization/personal'
    | '/purchase/bill/goods'
    | '/purchase/bill/service'
    | '/purchase/bill/status'
    | '/purchase/payment/approval'
    | '/purchase/payment/status'
    | '/sales/contract/items'
    | '/sales/contract/performance'
    | '/sales/contract/proposal'
    | '/sales/contract/register'
    | '/sales/contract/validate'
    | '/sales/tax-invoice/issue'
    | '/sales/tax-invoice/status'
    | '/hr/departments'
    | '/hr/employees'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/$'
    | '/_authenticated/'
    | '/_authenticated/accounting/accounts'
    | '/_authenticated/accounting/journal-entries'
    | '/_authenticated/common/code'
    | '/_authenticated/common/notice'
    | '/_authenticated/errors/$error'
    | '/_authenticated/purchase/collection'
    | '/_authenticated/purchase/order'
    | '/_authenticated/sales/collection'
    | '/_authenticated/sales/purchase-request'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/chats/'
    | '/_authenticated/customers/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/eval/appraisal/review'
    | '/_authenticated/eval/appraisal/self'
    | '/_authenticated/eval/goal/register'
    | '/_authenticated/eval/progress/evaluatee'
    | '/_authenticated/eval/progress/status'
    | '/_authenticated/finance/card/billing'
    | '/_authenticated/finance/card/status'
    | '/_authenticated/finance/card/usage'
    | '/_authenticated/finance/voucher/by-account'
    | '/_authenticated/finance/voucher/by-date'
    | '/_authenticated/ga/expense/congratulation'
    | '/_authenticated/ga/expense/disbursement'
    | '/_authenticated/ga/expense/meal-ticket'
    | '/_authenticated/ga/expense/transport'
    | '/_authenticated/ga/expense/tuition'
    | '/_authenticated/ga/expense/vehicle-subsidy'
    | '/_authenticated/ga/seal/corporate-apply'
    | '/_authenticated/ga/seal/e-contract'
    | '/_authenticated/ga/seal/fingerprint-export'
    | '/_authenticated/ga/seal/use-apply'
    | '/_authenticated/ga/seal/use-export'
    | '/_authenticated/hr/attendance/leave-apply'
    | '/_authenticated/hr/attendance/leave-status'
    | '/_authenticated/hr/attendance/overtime-apply'
    | '/_authenticated/hr/attendance/register'
    | '/_authenticated/hr/attendance/view'
    | '/_authenticated/hr/education/cert-apply'
    | '/_authenticated/hr/education/external-apply'
    | '/_authenticated/hr/education/history'
    | '/_authenticated/hr/payroll/expense-statement'
    | '/_authenticated/hr/payroll/incentive-status'
    | '/_authenticated/hr/payroll/payslip'
    | '/_authenticated/hr/personal/education'
    | '/_authenticated/hr/personal/history'
    | '/_authenticated/pm/activity/register'
    | '/_authenticated/pm/activity/view'
    | '/_authenticated/pm/budget/project-actual'
    | '/_authenticated/pm/budget/team-actual'
    | '/_authenticated/pm/utilization/personal'
    | '/_authenticated/purchase/bill/goods'
    | '/_authenticated/purchase/bill/service'
    | '/_authenticated/purchase/bill/status'
    | '/_authenticated/purchase/payment/approval'
    | '/_authenticated/purchase/payment/status'
    | '/_authenticated/sales/contract/items'
    | '/_authenticated/sales/contract/performance'
    | '/_authenticated/sales/contract/proposal'
    | '/_authenticated/sales/contract/register'
    | '/_authenticated/sales/contract/validate'
    | '/_authenticated/sales/tax-invoice/issue'
    | '/_authenticated/sales/tax-invoice/status'
    | '/_authenticated/hr/departments/'
    | '/_authenticated/hr/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/sales/purchase-request': {
      id: '/_authenticated/sales/purchase-request'
      path: '/sales/purchase-request'
      fullPath: '/sales/purchase-request'
      preLoaderRoute: typeof AuthenticatedSalesPurchaseRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/collection': {
      id: '/_authenticated/sales/collection'
      path: '/sales/collection'
      fullPath: '/sales/collection'
      preLoaderRoute: typeof AuthenticatedSalesCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/order': {
      id: '/_authenticated/purchase/order'
      path: '/purchase/order'
      fullPath: '/purchase/order'
      preLoaderRoute: typeof AuthenticatedPurchaseOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/collection': {
      id: '/_authenticated/purchase/collection'
      path: '/purchase/collection'
      fullPath: '/purchase/collection'
      preLoaderRoute: typeof AuthenticatedPurchaseCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/common/notice': {
      id: '/_authenticated/common/notice'
      path: '/common/notice'
      fullPath: '/common/notice'
      preLoaderRoute: typeof AuthenticatedCommonNoticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/common/code': {
      id: '/_authenticated/common/code'
      path: '/common/code'
      fullPath: '/common/code'
      preLoaderRoute: typeof AuthenticatedCommonCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/journal-entries': {
      id: '/_authenticated/accounting/journal-entries'
      path: '/accounting/journal-entries'
      fullPath: '/accounting/journal-entries'
      preLoaderRoute: typeof AuthenticatedAccountingJournalEntriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/accounts': {
      id: '/_authenticated/accounting/accounts'
      path: '/accounting/accounts'
      fullPath: '/accounting/accounts'
      preLoaderRoute: typeof AuthenticatedAccountingAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/employees/': {
      id: '/_authenticated/hr/employees/'
      path: '/hr/employees'
      fullPath: '/hr/employees/'
      preLoaderRoute: typeof AuthenticatedHrEmployeesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/departments/': {
      id: '/_authenticated/hr/departments/'
      path: '/hr/departments'
      fullPath: '/hr/departments/'
      preLoaderRoute: typeof AuthenticatedHrDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/tax-invoice/status': {
      id: '/_authenticated/sales/tax-invoice/status'
      path: '/sales/tax-invoice/status'
      fullPath: '/sales/tax-invoice/status'
      preLoaderRoute: typeof AuthenticatedSalesTaxInvoiceStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/tax-invoice/issue': {
      id: '/_authenticated/sales/tax-invoice/issue'
      path: '/sales/tax-invoice/issue'
      fullPath: '/sales/tax-invoice/issue'
      preLoaderRoute: typeof AuthenticatedSalesTaxInvoiceIssueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/contract/validate': {
      id: '/_authenticated/sales/contract/validate'
      path: '/sales/contract/validate'
      fullPath: '/sales/contract/validate'
      preLoaderRoute: typeof AuthenticatedSalesContractValidateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/contract/register': {
      id: '/_authenticated/sales/contract/register'
      path: '/sales/contract/register'
      fullPath: '/sales/contract/register'
      preLoaderRoute: typeof AuthenticatedSalesContractRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/contract/proposal': {
      id: '/_authenticated/sales/contract/proposal'
      path: '/sales/contract/proposal'
      fullPath: '/sales/contract/proposal'
      preLoaderRoute: typeof AuthenticatedSalesContractProposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/contract/performance': {
      id: '/_authenticated/sales/contract/performance'
      path: '/sales/contract/performance'
      fullPath: '/sales/contract/performance'
      preLoaderRoute: typeof AuthenticatedSalesContractPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/contract/items': {
      id: '/_authenticated/sales/contract/items'
      path: '/sales/contract/items'
      fullPath: '/sales/contract/items'
      preLoaderRoute: typeof AuthenticatedSalesContractItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/payment/status': {
      id: '/_authenticated/purchase/payment/status'
      path: '/purchase/payment/status'
      fullPath: '/purchase/payment/status'
      preLoaderRoute: typeof AuthenticatedPurchasePaymentStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/payment/approval': {
      id: '/_authenticated/purchase/payment/approval'
      path: '/purchase/payment/approval'
      fullPath: '/purchase/payment/approval'
      preLoaderRoute: typeof AuthenticatedPurchasePaymentApprovalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/bill/status': {
      id: '/_authenticated/purchase/bill/status'
      path: '/purchase/bill/status'
      fullPath: '/purchase/bill/status'
      preLoaderRoute: typeof AuthenticatedPurchaseBillStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/bill/service': {
      id: '/_authenticated/purchase/bill/service'
      path: '/purchase/bill/service'
      fullPath: '/purchase/bill/service'
      preLoaderRoute: typeof AuthenticatedPurchaseBillServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase/bill/goods': {
      id: '/_authenticated/purchase/bill/goods'
      path: '/purchase/bill/goods'
      fullPath: '/purchase/bill/goods'
      preLoaderRoute: typeof AuthenticatedPurchaseBillGoodsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm/utilization/personal': {
      id: '/_authenticated/pm/utilization/personal'
      path: '/pm/utilization/personal'
      fullPath: '/pm/utilization/personal'
      preLoaderRoute: typeof AuthenticatedPmUtilizationPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm/budget/team-actual': {
      id: '/_authenticated/pm/budget/team-actual'
      path: '/pm/budget/team-actual'
      fullPath: '/pm/budget/team-actual'
      preLoaderRoute: typeof AuthenticatedPmBudgetTeamActualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm/budget/project-actual': {
      id: '/_authenticated/pm/budget/project-actual'
      path: '/pm/budget/project-actual'
      fullPath: '/pm/budget/project-actual'
      preLoaderRoute: typeof AuthenticatedPmBudgetProjectActualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm/activity/view': {
      id: '/_authenticated/pm/activity/view'
      path: '/pm/activity/view'
      fullPath: '/pm/activity/view'
      preLoaderRoute: typeof AuthenticatedPmActivityViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pm/activity/register': {
      id: '/_authenticated/pm/activity/register'
      path: '/pm/activity/register'
      fullPath: '/pm/activity/register'
      preLoaderRoute: typeof AuthenticatedPmActivityRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/personal/history': {
      id: '/_authenticated/hr/personal/history'
      path: '/hr/personal/history'
      fullPath: '/hr/personal/history'
      preLoaderRoute: typeof AuthenticatedHrPersonalHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/personal/education': {
      id: '/_authenticated/hr/personal/education'
      path: '/hr/personal/education'
      fullPath: '/hr/personal/education'
      preLoaderRoute: typeof AuthenticatedHrPersonalEducationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/payroll/payslip': {
      id: '/_authenticated/hr/payroll/payslip'
      path: '/hr/payroll/payslip'
      fullPath: '/hr/payroll/payslip'
      preLoaderRoute: typeof AuthenticatedHrPayrollPayslipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/payroll/incentive-status': {
      id: '/_authenticated/hr/payroll/incentive-status'
      path: '/hr/payroll/incentive-status'
      fullPath: '/hr/payroll/incentive-status'
      preLoaderRoute: typeof AuthenticatedHrPayrollIncentiveStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/payroll/expense-statement': {
      id: '/_authenticated/hr/payroll/expense-statement'
      path: '/hr/payroll/expense-statement'
      fullPath: '/hr/payroll/expense-statement'
      preLoaderRoute: typeof AuthenticatedHrPayrollExpenseStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/education/history': {
      id: '/_authenticated/hr/education/history'
      path: '/hr/education/history'
      fullPath: '/hr/education/history'
      preLoaderRoute: typeof AuthenticatedHrEducationHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/education/external-apply': {
      id: '/_authenticated/hr/education/external-apply'
      path: '/hr/education/external-apply'
      fullPath: '/hr/education/external-apply'
      preLoaderRoute: typeof AuthenticatedHrEducationExternalApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/education/cert-apply': {
      id: '/_authenticated/hr/education/cert-apply'
      path: '/hr/education/cert-apply'
      fullPath: '/hr/education/cert-apply'
      preLoaderRoute: typeof AuthenticatedHrEducationCertApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance/view': {
      id: '/_authenticated/hr/attendance/view'
      path: '/hr/attendance/view'
      fullPath: '/hr/attendance/view'
      preLoaderRoute: typeof AuthenticatedHrAttendanceViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance/register': {
      id: '/_authenticated/hr/attendance/register'
      path: '/hr/attendance/register'
      fullPath: '/hr/attendance/register'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance/overtime-apply': {
      id: '/_authenticated/hr/attendance/overtime-apply'
      path: '/hr/attendance/overtime-apply'
      fullPath: '/hr/attendance/overtime-apply'
      preLoaderRoute: typeof AuthenticatedHrAttendanceOvertimeApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance/leave-status': {
      id: '/_authenticated/hr/attendance/leave-status'
      path: '/hr/attendance/leave-status'
      fullPath: '/hr/attendance/leave-status'
      preLoaderRoute: typeof AuthenticatedHrAttendanceLeaveStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/attendance/leave-apply': {
      id: '/_authenticated/hr/attendance/leave-apply'
      path: '/hr/attendance/leave-apply'
      fullPath: '/hr/attendance/leave-apply'
      preLoaderRoute: typeof AuthenticatedHrAttendanceLeaveApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/seal/use-export': {
      id: '/_authenticated/ga/seal/use-export'
      path: '/ga/seal/use-export'
      fullPath: '/ga/seal/use-export'
      preLoaderRoute: typeof AuthenticatedGaSealUseExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/seal/use-apply': {
      id: '/_authenticated/ga/seal/use-apply'
      path: '/ga/seal/use-apply'
      fullPath: '/ga/seal/use-apply'
      preLoaderRoute: typeof AuthenticatedGaSealUseApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/seal/fingerprint-export': {
      id: '/_authenticated/ga/seal/fingerprint-export'
      path: '/ga/seal/fingerprint-export'
      fullPath: '/ga/seal/fingerprint-export'
      preLoaderRoute: typeof AuthenticatedGaSealFingerprintExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/seal/e-contract': {
      id: '/_authenticated/ga/seal/e-contract'
      path: '/ga/seal/e-contract'
      fullPath: '/ga/seal/e-contract'
      preLoaderRoute: typeof AuthenticatedGaSealEContractRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/seal/corporate-apply': {
      id: '/_authenticated/ga/seal/corporate-apply'
      path: '/ga/seal/corporate-apply'
      fullPath: '/ga/seal/corporate-apply'
      preLoaderRoute: typeof AuthenticatedGaSealCorporateApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/vehicle-subsidy': {
      id: '/_authenticated/ga/expense/vehicle-subsidy'
      path: '/ga/expense/vehicle-subsidy'
      fullPath: '/ga/expense/vehicle-subsidy'
      preLoaderRoute: typeof AuthenticatedGaExpenseVehicleSubsidyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/tuition': {
      id: '/_authenticated/ga/expense/tuition'
      path: '/ga/expense/tuition'
      fullPath: '/ga/expense/tuition'
      preLoaderRoute: typeof AuthenticatedGaExpenseTuitionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/transport': {
      id: '/_authenticated/ga/expense/transport'
      path: '/ga/expense/transport'
      fullPath: '/ga/expense/transport'
      preLoaderRoute: typeof AuthenticatedGaExpenseTransportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/meal-ticket': {
      id: '/_authenticated/ga/expense/meal-ticket'
      path: '/ga/expense/meal-ticket'
      fullPath: '/ga/expense/meal-ticket'
      preLoaderRoute: typeof AuthenticatedGaExpenseMealTicketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/disbursement': {
      id: '/_authenticated/ga/expense/disbursement'
      path: '/ga/expense/disbursement'
      fullPath: '/ga/expense/disbursement'
      preLoaderRoute: typeof AuthenticatedGaExpenseDisbursementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ga/expense/congratulation': {
      id: '/_authenticated/ga/expense/congratulation'
      path: '/ga/expense/congratulation'
      fullPath: '/ga/expense/congratulation'
      preLoaderRoute: typeof AuthenticatedGaExpenseCongratulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/voucher/by-date': {
      id: '/_authenticated/finance/voucher/by-date'
      path: '/finance/voucher/by-date'
      fullPath: '/finance/voucher/by-date'
      preLoaderRoute: typeof AuthenticatedFinanceVoucherByDateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/voucher/by-account': {
      id: '/_authenticated/finance/voucher/by-account'
      path: '/finance/voucher/by-account'
      fullPath: '/finance/voucher/by-account'
      preLoaderRoute: typeof AuthenticatedFinanceVoucherByAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/card/usage': {
      id: '/_authenticated/finance/card/usage'
      path: '/finance/card/usage'
      fullPath: '/finance/card/usage'
      preLoaderRoute: typeof AuthenticatedFinanceCardUsageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/card/status': {
      id: '/_authenticated/finance/card/status'
      path: '/finance/card/status'
      fullPath: '/finance/card/status'
      preLoaderRoute: typeof AuthenticatedFinanceCardStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/card/billing': {
      id: '/_authenticated/finance/card/billing'
      path: '/finance/card/billing'
      fullPath: '/finance/card/billing'
      preLoaderRoute: typeof AuthenticatedFinanceCardBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval/progress/status': {
      id: '/_authenticated/eval/progress/status'
      path: '/eval/progress/status'
      fullPath: '/eval/progress/status'
      preLoaderRoute: typeof AuthenticatedEvalProgressStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval/progress/evaluatee': {
      id: '/_authenticated/eval/progress/evaluatee'
      path: '/eval/progress/evaluatee'
      fullPath: '/eval/progress/evaluatee'
      preLoaderRoute: typeof AuthenticatedEvalProgressEvaluateeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval/goal/register': {
      id: '/_authenticated/eval/goal/register'
      path: '/eval/goal/register'
      fullPath: '/eval/goal/register'
      preLoaderRoute: typeof AuthenticatedEvalGoalRegisterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval/appraisal/self': {
      id: '/_authenticated/eval/appraisal/self'
      path: '/eval/appraisal/self'
      fullPath: '/eval/appraisal/self'
      preLoaderRoute: typeof AuthenticatedEvalAppraisalSelfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eval/appraisal/review': {
      id: '/_authenticated/eval/appraisal/review'
      path: '/eval/appraisal/review'
      fullPath: '/eval/appraisal/review'
      preLoaderRoute: typeof AuthenticatedEvalAppraisalReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountingAccountsRoute: typeof AuthenticatedAccountingAccountsRoute
  AuthenticatedAccountingJournalEntriesRoute: typeof AuthenticatedAccountingJournalEntriesRoute
  AuthenticatedCommonCodeRoute: typeof AuthenticatedCommonCodeRoute
  AuthenticatedCommonNoticeRoute: typeof AuthenticatedCommonNoticeRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPurchaseCollectionRoute: typeof AuthenticatedPurchaseCollectionRoute
  AuthenticatedPurchaseOrderRoute: typeof AuthenticatedPurchaseOrderRoute
  AuthenticatedSalesCollectionRoute: typeof AuthenticatedSalesCollectionRoute
  AuthenticatedSalesPurchaseRequestRoute: typeof AuthenticatedSalesPurchaseRequestRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedEvalAppraisalReviewRoute: typeof AuthenticatedEvalAppraisalReviewRoute
  AuthenticatedEvalAppraisalSelfRoute: typeof AuthenticatedEvalAppraisalSelfRoute
  AuthenticatedEvalGoalRegisterRoute: typeof AuthenticatedEvalGoalRegisterRoute
  AuthenticatedEvalProgressEvaluateeRoute: typeof AuthenticatedEvalProgressEvaluateeRoute
  AuthenticatedEvalProgressStatusRoute: typeof AuthenticatedEvalProgressStatusRoute
  AuthenticatedFinanceCardBillingRoute: typeof AuthenticatedFinanceCardBillingRoute
  AuthenticatedFinanceCardStatusRoute: typeof AuthenticatedFinanceCardStatusRoute
  AuthenticatedFinanceCardUsageRoute: typeof AuthenticatedFinanceCardUsageRoute
  AuthenticatedFinanceVoucherByAccountRoute: typeof AuthenticatedFinanceVoucherByAccountRoute
  AuthenticatedFinanceVoucherByDateRoute: typeof AuthenticatedFinanceVoucherByDateRoute
  AuthenticatedGaExpenseCongratulationRoute: typeof AuthenticatedGaExpenseCongratulationRoute
  AuthenticatedGaExpenseDisbursementRoute: typeof AuthenticatedGaExpenseDisbursementRoute
  AuthenticatedGaExpenseMealTicketRoute: typeof AuthenticatedGaExpenseMealTicketRoute
  AuthenticatedGaExpenseTransportRoute: typeof AuthenticatedGaExpenseTransportRoute
  AuthenticatedGaExpenseTuitionRoute: typeof AuthenticatedGaExpenseTuitionRoute
  AuthenticatedGaExpenseVehicleSubsidyRoute: typeof AuthenticatedGaExpenseVehicleSubsidyRoute
  AuthenticatedGaSealCorporateApplyRoute: typeof AuthenticatedGaSealCorporateApplyRoute
  AuthenticatedGaSealEContractRoute: typeof AuthenticatedGaSealEContractRoute
  AuthenticatedGaSealFingerprintExportRoute: typeof AuthenticatedGaSealFingerprintExportRoute
  AuthenticatedGaSealUseApplyRoute: typeof AuthenticatedGaSealUseApplyRoute
  AuthenticatedGaSealUseExportRoute: typeof AuthenticatedGaSealUseExportRoute
  AuthenticatedHrAttendanceLeaveApplyRoute: typeof AuthenticatedHrAttendanceLeaveApplyRoute
  AuthenticatedHrAttendanceLeaveStatusRoute: typeof AuthenticatedHrAttendanceLeaveStatusRoute
  AuthenticatedHrAttendanceOvertimeApplyRoute: typeof AuthenticatedHrAttendanceOvertimeApplyRoute
  AuthenticatedHrAttendanceRegisterRoute: typeof AuthenticatedHrAttendanceRegisterRoute
  AuthenticatedHrAttendanceViewRoute: typeof AuthenticatedHrAttendanceViewRoute
  AuthenticatedHrEducationCertApplyRoute: typeof AuthenticatedHrEducationCertApplyRoute
  AuthenticatedHrEducationExternalApplyRoute: typeof AuthenticatedHrEducationExternalApplyRoute
  AuthenticatedHrEducationHistoryRoute: typeof AuthenticatedHrEducationHistoryRoute
  AuthenticatedHrPayrollExpenseStatementRoute: typeof AuthenticatedHrPayrollExpenseStatementRoute
  AuthenticatedHrPayrollIncentiveStatusRoute: typeof AuthenticatedHrPayrollIncentiveStatusRoute
  AuthenticatedHrPayrollPayslipRoute: typeof AuthenticatedHrPayrollPayslipRoute
  AuthenticatedHrPersonalEducationRoute: typeof AuthenticatedHrPersonalEducationRoute
  AuthenticatedHrPersonalHistoryRoute: typeof AuthenticatedHrPersonalHistoryRoute
  AuthenticatedPmActivityRegisterRoute: typeof AuthenticatedPmActivityRegisterRoute
  AuthenticatedPmActivityViewRoute: typeof AuthenticatedPmActivityViewRoute
  AuthenticatedPmBudgetProjectActualRoute: typeof AuthenticatedPmBudgetProjectActualRoute
  AuthenticatedPmBudgetTeamActualRoute: typeof AuthenticatedPmBudgetTeamActualRoute
  AuthenticatedPmUtilizationPersonalRoute: typeof AuthenticatedPmUtilizationPersonalRoute
  AuthenticatedPurchaseBillGoodsRoute: typeof AuthenticatedPurchaseBillGoodsRoute
  AuthenticatedPurchaseBillServiceRoute: typeof AuthenticatedPurchaseBillServiceRoute
  AuthenticatedPurchaseBillStatusRoute: typeof AuthenticatedPurchaseBillStatusRoute
  AuthenticatedPurchasePaymentApprovalRoute: typeof AuthenticatedPurchasePaymentApprovalRoute
  AuthenticatedPurchasePaymentStatusRoute: typeof AuthenticatedPurchasePaymentStatusRoute
  AuthenticatedSalesContractItemsRoute: typeof AuthenticatedSalesContractItemsRoute
  AuthenticatedSalesContractPerformanceRoute: typeof AuthenticatedSalesContractPerformanceRoute
  AuthenticatedSalesContractProposalRoute: typeof AuthenticatedSalesContractProposalRoute
  AuthenticatedSalesContractRegisterRoute: typeof AuthenticatedSalesContractRegisterRoute
  AuthenticatedSalesContractValidateRoute: typeof AuthenticatedSalesContractValidateRoute
  AuthenticatedSalesTaxInvoiceIssueRoute: typeof AuthenticatedSalesTaxInvoiceIssueRoute
  AuthenticatedSalesTaxInvoiceStatusRoute: typeof AuthenticatedSalesTaxInvoiceStatusRoute
  AuthenticatedHrDepartmentsIndexRoute: typeof AuthenticatedHrDepartmentsIndexRoute
  AuthenticatedHrEmployeesIndexRoute: typeof AuthenticatedHrEmployeesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountingAccountsRoute: AuthenticatedAccountingAccountsRoute,
  AuthenticatedAccountingJournalEntriesRoute:
    AuthenticatedAccountingJournalEntriesRoute,
  AuthenticatedCommonCodeRoute: AuthenticatedCommonCodeRoute,
  AuthenticatedCommonNoticeRoute: AuthenticatedCommonNoticeRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPurchaseCollectionRoute: AuthenticatedPurchaseCollectionRoute,
  AuthenticatedPurchaseOrderRoute: AuthenticatedPurchaseOrderRoute,
  AuthenticatedSalesCollectionRoute: AuthenticatedSalesCollectionRoute,
  AuthenticatedSalesPurchaseRequestRoute:
    AuthenticatedSalesPurchaseRequestRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedEvalAppraisalReviewRoute: AuthenticatedEvalAppraisalReviewRoute,
  AuthenticatedEvalAppraisalSelfRoute: AuthenticatedEvalAppraisalSelfRoute,
  AuthenticatedEvalGoalRegisterRoute: AuthenticatedEvalGoalRegisterRoute,
  AuthenticatedEvalProgressEvaluateeRoute:
    AuthenticatedEvalProgressEvaluateeRoute,
  AuthenticatedEvalProgressStatusRoute: AuthenticatedEvalProgressStatusRoute,
  AuthenticatedFinanceCardBillingRoute: AuthenticatedFinanceCardBillingRoute,
  AuthenticatedFinanceCardStatusRoute: AuthenticatedFinanceCardStatusRoute,
  AuthenticatedFinanceCardUsageRoute: AuthenticatedFinanceCardUsageRoute,
  AuthenticatedFinanceVoucherByAccountRoute:
    AuthenticatedFinanceVoucherByAccountRoute,
  AuthenticatedFinanceVoucherByDateRoute:
    AuthenticatedFinanceVoucherByDateRoute,
  AuthenticatedGaExpenseCongratulationRoute:
    AuthenticatedGaExpenseCongratulationRoute,
  AuthenticatedGaExpenseDisbursementRoute:
    AuthenticatedGaExpenseDisbursementRoute,
  AuthenticatedGaExpenseMealTicketRoute: AuthenticatedGaExpenseMealTicketRoute,
  AuthenticatedGaExpenseTransportRoute: AuthenticatedGaExpenseTransportRoute,
  AuthenticatedGaExpenseTuitionRoute: AuthenticatedGaExpenseTuitionRoute,
  AuthenticatedGaExpenseVehicleSubsidyRoute:
    AuthenticatedGaExpenseVehicleSubsidyRoute,
  AuthenticatedGaSealCorporateApplyRoute:
    AuthenticatedGaSealCorporateApplyRoute,
  AuthenticatedGaSealEContractRoute: AuthenticatedGaSealEContractRoute,
  AuthenticatedGaSealFingerprintExportRoute:
    AuthenticatedGaSealFingerprintExportRoute,
  AuthenticatedGaSealUseApplyRoute: AuthenticatedGaSealUseApplyRoute,
  AuthenticatedGaSealUseExportRoute: AuthenticatedGaSealUseExportRoute,
  AuthenticatedHrAttendanceLeaveApplyRoute:
    AuthenticatedHrAttendanceLeaveApplyRoute,
  AuthenticatedHrAttendanceLeaveStatusRoute:
    AuthenticatedHrAttendanceLeaveStatusRoute,
  AuthenticatedHrAttendanceOvertimeApplyRoute:
    AuthenticatedHrAttendanceOvertimeApplyRoute,
  AuthenticatedHrAttendanceRegisterRoute:
    AuthenticatedHrAttendanceRegisterRoute,
  AuthenticatedHrAttendanceViewRoute: AuthenticatedHrAttendanceViewRoute,
  AuthenticatedHrEducationCertApplyRoute:
    AuthenticatedHrEducationCertApplyRoute,
  AuthenticatedHrEducationExternalApplyRoute:
    AuthenticatedHrEducationExternalApplyRoute,
  AuthenticatedHrEducationHistoryRoute: AuthenticatedHrEducationHistoryRoute,
  AuthenticatedHrPayrollExpenseStatementRoute:
    AuthenticatedHrPayrollExpenseStatementRoute,
  AuthenticatedHrPayrollIncentiveStatusRoute:
    AuthenticatedHrPayrollIncentiveStatusRoute,
  AuthenticatedHrPayrollPayslipRoute: AuthenticatedHrPayrollPayslipRoute,
  AuthenticatedHrPersonalEducationRoute: AuthenticatedHrPersonalEducationRoute,
  AuthenticatedHrPersonalHistoryRoute: AuthenticatedHrPersonalHistoryRoute,
  AuthenticatedPmActivityRegisterRoute: AuthenticatedPmActivityRegisterRoute,
  AuthenticatedPmActivityViewRoute: AuthenticatedPmActivityViewRoute,
  AuthenticatedPmBudgetProjectActualRoute:
    AuthenticatedPmBudgetProjectActualRoute,
  AuthenticatedPmBudgetTeamActualRoute: AuthenticatedPmBudgetTeamActualRoute,
  AuthenticatedPmUtilizationPersonalRoute:
    AuthenticatedPmUtilizationPersonalRoute,
  AuthenticatedPurchaseBillGoodsRoute: AuthenticatedPurchaseBillGoodsRoute,
  AuthenticatedPurchaseBillServiceRoute: AuthenticatedPurchaseBillServiceRoute,
  AuthenticatedPurchaseBillStatusRoute: AuthenticatedPurchaseBillStatusRoute,
  AuthenticatedPurchasePaymentApprovalRoute:
    AuthenticatedPurchasePaymentApprovalRoute,
  AuthenticatedPurchasePaymentStatusRoute:
    AuthenticatedPurchasePaymentStatusRoute,
  AuthenticatedSalesContractItemsRoute: AuthenticatedSalesContractItemsRoute,
  AuthenticatedSalesContractPerformanceRoute:
    AuthenticatedSalesContractPerformanceRoute,
  AuthenticatedSalesContractProposalRoute:
    AuthenticatedSalesContractProposalRoute,
  AuthenticatedSalesContractRegisterRoute:
    AuthenticatedSalesContractRegisterRoute,
  AuthenticatedSalesContractValidateRoute:
    AuthenticatedSalesContractValidateRoute,
  AuthenticatedSalesTaxInvoiceIssueRoute:
    AuthenticatedSalesTaxInvoiceIssueRoute,
  AuthenticatedSalesTaxInvoiceStatusRoute:
    AuthenticatedSalesTaxInvoiceStatusRoute,
  AuthenticatedHrDepartmentsIndexRoute: AuthenticatedHrDepartmentsIndexRoute,
  AuthenticatedHrEmployeesIndexRoute: AuthenticatedHrEmployeesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
